export const PRERENDER_ROUTES = [
    '/',
    '/hizmetler',
    '/didim-klima-tamiri',
    '/didim-klima-bakimi',
    '/didim-klima-montaji',
    '/altinkum-klima-servisi',
    '/akbuk-klima-servisi',
    '/bozbuk-klima-servisi',
    '/didim-hisense-klima-servisi',
    '/didim-vrf-servisi',
    '/didim-isi-pompasi-servisi',
    '/didim-gunes-enerjisi-sistemleri',
    '/didim-soguk-hava-deposu-servisi',
    '/didim-klima-gaz-dolumu',
    '/hakkimizda',
    '/iletisim',
];
