export const landingPages = {
    tamiri: {
        slug: 'didim-klima-tamiri',
        title: 'Didim Klima Tamiri | 7/24 Arıza Servisi | Pusula İklimlendirme',
        description: 'Didim ve Aydın\'da split, salon ve ticari klima tamiri. Aynı gün arıza servisi, gaz dolumu, 7/24 acil destek. Pusula İklimlendirme — garantili işçilik.',
        h1: 'Didim Klima Tamiri',
        subtitle: 'Split, salon ve ticari tip klimalarda hızlı arıza tespiti ve garantili onarım.',
        intro: [
            'Pusula İklimlendirme olarak Didim, Altınkum, Akbük ve Aydın genelinde klima tamiri hizmeti sunuyoruz. Soğutmama, su damlatma, anormal ses veya koku gibi arızalarda aynı gün müdahale hedefliyoruz.',
            'Hisense ve Quatech klima sistemlerinde yetkili servis desteği sunuyoruz. Diğer marka klimalarda da bakım ve arıza desteği sağlıyor; cihazın marka, model ve garanti durumuna göre işlem kapsamını netleştiriyoruz.',
        ],
        features: [
            '7/24 acil klima arıza servisi',
            'Split, multi ve VRF sistem tamiri',
            'Gaz kaçağı tespiti ve gaz dolumu',
            'Kompresör, fan ve kart arızası onarımı',
            'Su damlatma ve drenaj sorunları',
            'Tüm marka ve modellere servis',
        ],
        steps: [
            { title: 'Arıza bildirimi', desc: 'Telefon veya form ile bize ulaşın, arızayı kısaca anlatın.' },
            { title: 'Hızlı yönlendirme', desc: 'Didim ve çevresindeki en yakın teknisyenimiz yönlendirilir.' },
            { title: 'Yerinde teşhis', desc: 'Arıza kaynağı tespit edilir, onayınızla onarım başlar.' },
            { title: 'Garantili teslim', desc: 'Test edilip çalışır halde teslim edilir, 1 yıl garanti verilir.' },
        ],
        faqs: [
            {
                q: 'Didim\'de klima tamiri ne kadar sürer?',
                a: 'Basit arızalar genellikle aynı gün içinde giderilir. Orijinal yedek parça temini gerektiren durumlarda süre arıza tipine göre değişir; sizi önceden bilgilendiririz.',
            },
            {
                q: 'Hangi arızalarda servis çağırmalıyım?',
                a: 'Soğutmama veya ısıtmama, su damlatma, anormal ses, koku, sık sigorta attırma veya kumanda yanıt vermeme durumlarında servis çağırmanızı öneririz.',
            },
            {
                q: 'Yedek parça garantisi var mı?',
                a: 'Evet. Kullanılan orijinal yedek parçalar ve işçilik 1 yıl Pusula İklimlendirme garantisi kapsamındadır.',
            },
        ],
        related: ['bakimi', 'montaji'],
    },
    bakimi: {
        slug: 'didim-klima-bakimi',
        title: 'Didim Klima Bakımı | Periyodik Bakım & Filtre Temizliği | Pusula',
        description: 'Didim\'de klima bakımı, filtre temizliği ve sezon öncesi servis. Yaz/kış bakım paketleri, gaz kontrolü. Pusula İklimlendirme ile verimli iklimlendirme.',
        h1: 'Didim Klima Bakımı',
        subtitle: 'Yaz ve kış sezonu öncesi periyodik bakım ile verimli ve sağlıklı iklimlendirme.',
        intro: [
            'Didim\'de klima bakımı, cihazınızın ömrünü uzatır ve enerji tüketimini düşürür. Pusula İklimlendirme olarak filtre temizliği, gaz basıncı kontrolü, drenaj hattı bakımı ve genel performans testini kapsayan periyodik bakım paketleri sunuyoruz.',
            'Ev, yazlık, otel, restoran ve iş yerlerinde split klima, salon tipi ve VRF sistemlerin bakımını gerçekleştiriyoruz. Altınkum, Akbük ve Mavişehir dahil Didim genelinde hizmet veriyoruz.',
            'Hisense ve Quatech klima, Üntes ve Midea VRF sistemlerindeki yetkili servis kapsamımıza göre bakım planlıyoruz. Daikin VRV / VRF sistemleriyle çalışmalarımız proje odaklı iş ortaklığı kapsamındadır.',
        ],
        features: [
            'Filtre temizliği ve dezenfeksiyon',
            'Gaz basıncı kontrolü ve kaçak testi',
            'Drenaj hattı temizliği',
            'Elektronik kart ve sensör kontrolü',
            'Enerji verimliliği testi',
            'Yaz ve kış sezonu bakım paketleri',
        ],
        steps: [
            { title: 'Randevu', desc: 'Size uygun gün ve saatte bakım randevusu oluşturulur.' },
            { title: 'İç ve dış ünite kontrolü', desc: 'Filtre, fan, boru bağlantıları ve drenaj hattı incelenir.' },
            { title: 'Temizlik ve ayar', desc: 'Gerekli temizlik yapılır, gaz ve performans kontrol edilir.' },
            { title: 'Rapor ve öneri', desc: 'Cihaz durumu hakkında bilgi verilir, gerekirse tamir önerilir.' },
        ],
        faqs: [
            {
                q: 'Klima bakımı yılda kaç kez yapılmalı?',
                a: 'Didim\'in sıcak ikliminde yılda en az 2 kez — yaz sezonu öncesi ve kışa girmeden önce — bakım yaptırmanızı öneriyoruz.',
            },
            {
                q: 'Bakım yapılmazsa ne olur?',
                a: 'Kirli filtreler verimi düşürür, enerji tüketimi artar. Drenaj tıkanıklığı su damlatmaya, ihmal edilen bakım ise erken arızalara yol açabilir.',
            },
            {
                q: 'Bakım fiyatları sabit mi?',
                a: 'Fiyat cihaz tipine ve adede göre değişir. Güncel bakım ücreti için bizi arayabilir veya form üzerinden teklif isteyebilirsiniz.',
            },
        ],
        related: ['tamiri', 'montaji'],
    },
    montaji: {
        slug: 'didim-klima-montaji',
        title: 'Didim Klima Montajı | Ücretsiz Keşif & Profesyonel Kurulum | Pusula',
        description: 'Didim\'de klima montajı ve split kurulum. Ücretsiz keşif, vakumlu montaj, estetik borulama. Ev, yazlık ve iş yerleri için profesyonel kurulum.',
        h1: 'Didim Klima Montajı',
        subtitle: 'Ücretsiz keşif, vakumlu montaj ve estetik borulama ile güvenli klima kurulumu.',
        intro: [
            'Didim ve çevresinde yeni klima montajı veya eski cihaz değişimi için profesyonel kurulum hizmeti sunuyoruz. Doğru montaj, klimanızın performansını ve ömrünü doğrudan etkiler — bu yüzden her projede vakumlu montaj ve sızdırmazlık testi uyguluyoruz.',
            'Ev, yazlık daire, villa, otel ve iş yerlerinde split klima montajı gerçekleştiriyoruz. Keşif sonrası en uygun iç-dış ünite konumunu birlikte belirliyor, temiz ve estetik borulama ile kurulumu tamamlıyoruz.',
            'Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis desteği sunuyoruz. Merkezi iklimlendirme ihtiyacında Üntes ve Midea VRF çözümlerini, Daikin VRV / VRF sistemlerinde ise proje odaklı iş ortaklığımızı değerlendiriyoruz.',
        ],
        features: [
            'Ücretsiz keşif ve yerinde ölçüm',
            'Vakumlu profesyonel montaj',
            'Estetik bakır borulama',
            'İç-dış ünite optimum konumlandırma',
            'Elektrik bağlantısı ve test',
            'Split, multi split ve salon tipi montaj',
        ],
        steps: [
            { title: 'Ücretsiz keşif', desc: 'Adresinize gelerek altyapı, metrekare ve cihaz kapasitesini değerlendiririz.' },
            { title: 'Teklif ve planlama', desc: 'Montaj noktası, borulama güzergahı ve tarih birlikte belirlenir.' },
            { title: 'Profesyonel kurulum', desc: 'Vakum, sabitleme, borulama ve elektrik bağlantıları tamamlanır.' },
            { title: 'Test ve teslim', desc: 'Soğutma/ısıtma testi yapılır, kullanım bilgisi verilir.' },
        ],
        faqs: [
            {
                q: 'Didim\'de klima montajı ne kadar sürer?',
                a: 'Standart split klima montajı genellikle aynı gün tamamlanır. Multi split veya zorlu güzergahlı projelerde süre keşif sonrası netleştirilir.',
            },
            {
                q: 'Keşif gerçekten ücretsiz mi?',
                a: 'Evet. Didim ve yakın çevresinde keşif hizmetimiz ücretsizdir. Keşif sonrası net fiyat teklifi sunulur.',
            },
            {
                q: 'Kendi cihazımı getirsem montaj yapar mısınız?',
                a: 'Evet. Satın aldığınız split klimanın montajını da gerçekleştiriyoruz. Cihazın montaja uygun olduğundan keşifte emin oluyoruz.',
            },
        ],
        related: ['tamiri', 'bakimi'],
    },
    altinkum: {
        slug: 'altinkum-klima-servisi',
        title: 'Altınkum Klima Servisi | Tamiri, Bakım & Montaj | Pusula Didim',
        description: 'Altınkum\'da klima tamiri, bakımı ve montajı. Yazlık daireler ve sahil bölgesi için aynı gün servis. Pusula İklimlendirme Didim.',
        h1: 'Altınkum Klima Servisi',
        subtitle: 'Altınkum ve sahil bölgesinde klima tamiri, bakımı ve montajı — aynı gün servis.',
        ctaHeading: 'Altınkum\'da Klimanız İçin Yanınızdayız',
        intro: [
            'Altınkum, Didim\'in en yoğun konut ve tatil bölgelerinden biri. Yazlık daireler, apart oteller ve sahil şeridindeki işletmelerde split klima sistemleri yıl boyunca yoğun kullanılıyor. Pusula İklimlendirme olarak Altınkum\'da klima tamiri, periyodik bakım ve yeni cihaz montajı hizmeti sunuyoruz.',
            'Didim merkezdeki atölyemizden hareket eden mobil servis ekibimiz Altınkum\'a düzenli olarak çıkış yapıyor. Sezon öncesi bakım, acil arıza müdahalesi veya yeni klima kurulumu için bizi aramanız yeterli.',
        ],
        features: [
            'Altınkum\'da aynı gün klima tamiri',
            'Yazlık ve apart daire bakım paketleri',
            'Split klima montajı ve gaz dolumu',
            'Otel ve restoran VRF servisi',
            'Sezon öncesi toplu bakım anlaşmaları',
            '7/24 acil arıza hattı',
        ],
        steps: [
            { title: 'Bize ulaşın', desc: 'Altınkum adresinizi ve arıza/bakım ihtiyacınızı telefon veya form ile bildirin.' },
            { title: 'Randevu planlama', desc: 'Altınkum hattımıza uygun gün ve saatte randevu oluşturulur.' },
            { title: 'Yerinde servis', desc: 'Teknisyenimiz adresinize gelir, işlemi yerinde tamamlar.' },
            { title: 'Garantili teslim', desc: 'Cihaz test edilir, orijinal yedek parça ve işçilik garantisi verilir.' },
        ],
        faqs: [
            {
                q: 'Altınkum\'a servis ne kadar sürede gelir?',
                a: 'Altınkum Didim merkeze yakın olduğu için çoğu talebe aynı gün müdahale ediyoruz. Acil arızalarda öncelikli yönlendirme yapılır.',
            },
            {
                q: 'Yazlık dairem için sezonluk bakım yapıyor musunuz?',
                a: 'Evet. Yaz sezonu öncesi Altınkum\'daki yazlıklar için filtre temizliği, gaz kontrolü ve genel bakım paketi sunuyoruz.',
            },
            {
                q: 'Hangi hizmetleri veriyorsunuz?',
                a: 'Klima tamiri, periyodik bakım, montaj, gaz dolumu ve VRF sistem servisi. Detaylar için Didim hizmet sayfalarımıza göz atabilirsiniz.',
            },
        ],
        related: ['tamiri', 'bakimi', 'montaji', 'akbuk', 'bozbuk'],
    },
    akbuk: {
        slug: 'akbuk-klima-servisi',
        title: 'Akbük Klima Servisi | Didim Merkeze Uzak Bölgeler | Pusula',
        description: 'Akbük\'te klima tamiri, bakımı ve montajı. Didim merkeze uzak bölgelere mobil servis — adresinize geliyoruz. Pusula İklimlendirme.',
        h1: 'Akbük Klima Servisi',
        subtitle: 'Didim merkeze uzak Akbük\'te klima tamiri, bakımı ve montajı — adresinize geliyoruz.',
        ctaHeading: 'Akbük\'te Klimanız İçin Yanınızdayız',
        intro: [
            'Akbük, Didim merkeze yaklaşık 20 km mesafede, sakin koyları ve yazlık siteleriyle bilinen bir bölge. Merkeze uzaklık nedeniyle birçok tüketici Akbük\'te güvenilir klima servisi bulmakta zorlanıyor — Pusula İklimlendirme bu boşluğu dolduruyor.',
            'Mobil servis araçlarımızla Akbük\'e düzenli çıkış yapıyoruz. Yazlık siteleri, villalar ve apart konutlarda split klima tamiri, bakımı ve montajı gerçekleştiriyoruz. Didim merkezdeki firmaların çoğu Akbük\'e servis vermezken biz bölgeyi aktif hizmet alanımız olarak kapsıyoruz.',
        ],
        features: [
            'Akbük\'e mobil servis — adresinize geliyoruz',
            'Didim merkeze uzak bölgelerde aktif hizmet',
            'Yazlık site ve villa klima bakımı',
            'Acil arıza müdahalesi',
            'Split klima montajı ve gaz dolumu',
            'Randevulu ve planlı servis çıkışları',
        ],
        steps: [
            { title: 'Talep oluşturun', desc: 'Akbük\'teki adresinizi ve ihtiyacınızı bize iletin.' },
            { title: 'Randevu onayı', desc: 'Akbük servis planımıza göre size en yakın gün belirlenir.' },
            { title: 'Mobil ekip yönlendirme', desc: 'Didim\'den hareket eden teknisyen ekibimiz Akbük\'e gelir.' },
            { title: 'Yerinde çözüm', desc: 'Tamir, bakım veya montaj adresinizde tamamlanır.' },
        ],
        faqs: [
            {
                q: 'Akbük\'e gerçekten servis geliyor mu?',
                a: 'Evet. Akbük, aktif hizmet verdiğimiz mahallelerden biridir. Haftalık planlı çıkışlarımız ve acil talepler için ayrı yönlendirmelerimiz vardır.',
            },
            {
                q: 'Didim merkezdeki servisler Akbük\'e neden gelmiyor?',
                a: 'Mesafe ve lojistik maliyet nedeniyle birçok firma yalnızca merkezde hizmet verir. Pusula olarak Akbük ve Bozbük dahil tüm Didim yarımadasını kapsıyoruz.',
            },
            {
                q: 'Akbük\'te montaj da yapıyor musunuz?',
                a: 'Evet. Yeni split klima montajı için ücretsiz keşif sonrası Akbük\'te kurulum gerçekleştiriyoruz.',
            },
        ],
        related: ['tamiri', 'bakimi', 'montaji', 'altinkum', 'bozbuk'],
    },
    bozbuk: {
        slug: 'bozbuk-klima-servisi',
        title: 'Bozbük Klima Servisi | Uzak Mahallelerde Mobil Servis | Pusula',
        description: 'Bozbük\'te klima tamiri, bakımı ve montajı. Didim\'in uzak mahallelerine mobil servis. Villa ve yazlık klimalar için yerinde hizmet.',
        h1: 'Bozbük Klima Servisi',
        subtitle: 'Didim\'in en uzak mahallelerinden Bozbük\'te klima tamiri, bakımı ve montajı.',
        ctaHeading: 'Bozbük\'te Klimanız İçin Yanınızdayız',
        intro: [
            'Bozbük, Didim merkeze en uzak mahallelerden biri. Sakin yapısı ve doğayla iç içe konumuyla tercih edilen bu bölgede klima servisi bulmak özellikle zor — en yakın servis genellikle Didim merkezde kalıyor.',
            'Pusula İklimlendirme olarak Bozbük\'e mobil servis hizmeti sunuyoruz. Yazlık evler, villalar ve küçük işletmelerde klima arızası, sezonluk bakım ve yeni cihaz montajı için adresinize geliyoruz. Uzak mahalle olmanız servis almanıza engel değil.',
        ],
        features: [
            'Bozbük\'e özel mobil servis çıkışları',
            'Uzak mahallelerde yerinde tamir ve bakım',
            'Villa ve yazlık klima montajı',
            'Sezon öncesi bakım randevusu',
            'Acil arıza desteği',
            'Didim genelinde tek muhatap — merkeze gitmenize gerek yok',
        ],
        steps: [
            { title: 'İletişime geçin', desc: 'Bozbük\'teki konumunuzu ve talebinizi paylaşın.' },
            { title: 'Planlı randevu', desc: 'Bozbük servis rotamıza göre uygun tarih belirlenir.' },
            { title: 'Adresinize geliyoruz', desc: 'Mobil ekibimiz Bozbük\'e gelerek işlemi yerinde yapar.' },
            { title: 'Garantili hizmet', desc: 'Tüm onarım ve bakım işlemleri garanti kapsamındadır.' },
        ],
        faqs: [
            {
                q: 'Bozbük\'e servis ücreti daha mı pahalı?',
                a: 'Mesafe farkı nedeniyle bazı işlemlerde lojistik ücreti uygulanabilir. Arama sırasında net fiyat bilgisi verilir, sürpriz maliyet olmaz.',
            },
            {
                q: 'Bozbük\'te ne sıklıkla servis çıkışı yapıyorsunuz?',
                a: 'Talep yoğunluğuna göre haftalık planlı çıkışlarımız vardır. Acil arızalarda mümkün olan en kısa sürede yönlendirme yapılır.',
            },
            {
                q: 'Hangi klima markalarına bakıyorsunuz?',
                a: 'Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis desteği sunuyoruz. Bozbük’te diğer marka split, salon ve ticari klimalar için de cihaz ve garanti durumuna göre bakım ve arıza desteği sağlıyoruz.',
            },
        ],
        related: ['tamiri', 'bakimi', 'montaji', 'altinkum', 'akbuk'],
    },
    split: {
        slug: 'didim-split-klima-servisi',
        title: 'Didim Split Klima | Hisense, Quatech ve Baymak | Pusula',
        description: 'Didim, Akbük ve Altınkum’da Hisense, Quatech ve Baymak split klima çözümleri. Satış, yerinde keşif, montaj, bakım ve arıza desteği.',
        h1: 'Didim Split Klima Sistemleri',
        subtitle: 'Ev, yazlık ve ofisler için doğru kapasite, düzenli montaj ve güvenilir servis.',
        ctaHeading: 'Split Klimanız İçin Doğru Cihaz ve Kurulum',
        intro: [
            'Pusula İklimlendirme, Didim ve çevresinde split klima satışı, montajı, bakımı ve arıza onarımı sunar. Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis olarak ihtiyacınıza uygun çözümü birlikte belirliyoruz.',
            'Baymak split klima çözümleriyle de çalışıyoruz. Cihaz seçimi, montaj ve bakım kapsamını kullanım ihtiyacınıza ve ürün modeline göre planlıyoruz.',
            'Metrekare, yalıtım, güneş alma durumu ve kullanım alışkanlıklarını değerlendirerek cihaz kapasitesi ve montaj yerini planlıyoruz. Duvar tipi split ve çok odalı kullanım ihtiyaçları için altyapıyı yerinde inceliyoruz.',
        ],
        answerBox: 'Didim’de Hisense ve Quatech yetkili bayi ve servis desteği ile Baymak split klima çözümleri sunuyoruz. Cihaz seçimi, keşif, montaj ve bakım hizmetlerini ihtiyacınıza göre planlıyoruz.',
        features: [
            'Hisense ve Quatech yetkili bayi ve servis',
            'Baymak split klima çözümleri',
            'Ev, yazlık ve ofis keşfi',
            'Kapasite ve montaj yeri değerlendirmesi',
            'Vakumlu montaj ve düzenli borulama',
            'Periyodik bakım ve arıza desteği',
            'Didim, Altınkum ve Akbük’te yerinde hizmet',
        ],
        steps: [
            { title: 'İhtiyaç ve keşif', desc: 'Alan, kullanım ve mevcut elektrik altyapısı yerinde incelenir.' },
            { title: 'Cihaz ve teklif', desc: 'Uygun kapasite, marka, montaj kapsamı ve fiyat teklifi birlikte netleştirilir.' },
            { title: 'Montaj', desc: 'İç ve dış ünite konumlandırılır; borulama, vakum ve bağlantı kontrolleri yapılır.' },
            { title: 'Teslim ve bakım', desc: 'Çalışma testi ve kullanım bilgilendirmesi sonrası bakım ihtiyaçları paylaşılır.' },
        ],
        faqs: [
            { q: 'Hangi split klima markalarıyla çalışıyorsunuz?', a: 'Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis desteğimiz var. Baymak split klima çözümleriyle de çalışıyoruz. Ürün seçimi ve işlem kapsamını cihaz modeline göre netleştiriyoruz.' },
            { q: 'Cihaz kapasitesini nasıl belirliyorsunuz?', a: 'Yalnızca metrekareye göre değil; yalıtım, güneş alma durumu, kişi sayısı ve kullanım ihtiyacını da keşifte değerlendiriyoruz.' },
            { q: 'Satış dışında bakım ve onarım da yapıyor musunuz?', a: 'Evet. Mevcut split klimalar için bakım, arıza tespiti ve montaj taleplerini de karşılıyoruz. Yetki ve garanti kapsamı markaya ve cihaza göre değerlendirilir.' },
        ],
        related: ['hisense', 'ticari', 'montaji', 'bakimi'],
        serviceName: 'Split Klima Satış, Montaj, Bakım ve Servis',
    },
    ticari: {
        slug: 'didim-ticari-klima-servisi',
        title: 'Didim Ticari Klima | Salon, Kaset ve Kanallı Sistemler | Pusula',
        description: 'Didim’de mağaza, restoran ve ofisler için ticari klima keşfi, satış, montaj ve bakım. Salon, kaset ve kanallı sistemler için projeli çözümler.',
        h1: 'Didim Ticari Klima Sistemleri',
        subtitle: 'Mağaza, restoran, ofis ve işletmeler için kullanıma uygun iklimlendirme çözümleri.',
        ctaHeading: 'İşletmenizin İklimlendirmesini Birlikte Planlayalım',
        intro: [
            'Ticari alanların iklimlendirme ihtiyacını işletme türü, çalışma saatleri, kişi yoğunluğu ve mekân yerleşimine göre değerlendiriyoruz. Didim ve Aydın çevresinde salon, kaset ve kanallı klima çözümleri için keşif, cihaz seçimi, montaj ve bakım hizmeti sunuyoruz.',
            'Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis kapsamımızla, kullanılacak cihazın ürün grubuna göre çözüm planlıyoruz. Daha geniş merkezi sistem ihtiyaçlarında Üntes ve Midea VRF desteğimizi, Daikin VRV / VRF sistemlerinde ise proje odaklı iş ortaklığımızı değerlendiriyoruz.',
            'Bağımsız ticari klima ile merkezi VRF / VRV sistemi arasındaki seçimi keşifte netleştiriyor; cihaz, altyapı, montaj ve bakım kapsamını teklifimizde açıklıyoruz.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de ticari klima ihtiyaçları için salon, kaset ve kanallı sistemlerde keşif, satış, montaj, bakım ve teknik destek sunar.',
        features: [
            'Salon, kaset ve kanallı klima çözümleri',
            'Mağaza, restoran ve ofis keşfi',
            'Kapasite, hava dağılımı ve altyapı planı',
            'Cihaz ve ürün kapsamına uygun marka seçimi',
            'Montaj, devreye alma ve çalışma kontrolü',
            'İşletme saatlerine uygun periyodik bakım',
        ],
        steps: [
            { title: 'İşletme keşfi', desc: 'Kullanım yoğunluğu, tavan yapısı, elektrik altyapısı ve montaj alanları incelenir.' },
            { title: 'Sistem ve teklif', desc: 'Salon, kaset, kanallı klima veya merkezi sistem ihtiyacı değerlendirilir; kapsam ve maliyet sunulur.' },
            { title: 'Planlı kurulum', desc: 'İşletme çalışmasını dikkate alan bir takvimle montaj ve bağlantı kontrolleri gerçekleştirilir.' },
            { title: 'Test ve bakım planı', desc: 'Çalışma değerleri kontrol edilir; kullanım yoğunluğuna göre bakım takvimi önerilir.' },
        ],
        faqs: [
            { q: 'Ticari klima ile VRF sistemi aynı şey mi?', a: 'Hayır. Ticari klima salon, kaset veya kanallı cihaz çözümlerini kapsayabilir. Birden fazla alanı merkezi olarak yönetmek gerektiğinde VRF / VRV sistemi ayrıca değerlendirilir.' },
            { q: 'Hangi markalarla çalışıyorsunuz?', a: 'Hisense ve Quatech klima sistemlerinde yetkili bayi ve servis desteğimiz bulunuyor. Üntes ve Midea VRF için yetkili destek, Daikin VRV / VRF için proje odaklı iş ortaklığı sunuyoruz; cihaz ve ürün kapsamı keşifte netleştirilir.' },
            { q: 'İşletmelere düzenli bakım planı yapıyor musunuz?', a: 'Evet. Cihaz sayısı, çalışma süresi ve kullanım yoğunluğunu değerlendirerek işletmeye uygun periyodik bakım planı hazırlıyoruz.' },
        ],
        related: ['split', 'vrf', 'bakimi', 'sogukHava'],
        serviceName: 'Ticari Klima Satış, Montaj, Bakım ve Servis',
    },
    hisense: {
        slug: 'didim-hisense-klima-servisi',
        title: 'Didim Hisense Klima Servisi ve Bayi | Pusula İklimlendirme',
        description: 'Didim Hisense klima yetkili bayi ve servis. Hisense klima satış, montaj, bakım, arıza onarım ve ücretsiz keşif için Pusula İklimlendirme.',
        h1: 'Didim Hisense Klima Servisi',
        subtitle: 'Hisense klima satış, montaj, bakım ve arıza onarımında Didim yetkili bayi ve servis desteği.',
        ctaHeading: 'Hisense Klima İçin Yetkili Servis ve Bayi Desteği',
        intro: [
            'Pusula İklimlendirme, Didim’de Hisense klima için yetkili bayi ve servis hizmeti sunar. Yeni klima alımı, kapasite seçimi, ücretsiz keşif, montaj ve servis süreçlerinde tek muhatap olarak yanınızdayız.',
            'Didim merkez, Altınkum, Akbük, Bozbük ve çevre mahallelerde Hisense split klima satış, kurulum, periyodik bakım ve arıza onarım taleplerini üretici standartlarına uygun şekilde karşılıyoruz.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de Hisense klima yetkili bayi ve servisidir. Satış, ücretsiz keşif, montaj, bakım ve arıza onarım hizmeti verir.',
        features: [
            'Hisense klima yetkili bayi',
            'Hisense klima yetkili servis',
            'Ücretsiz keşif ve kapasite önerisi',
            '4 metre borulama dahil montaj seçenekleri',
            'Periyodik bakım ve arıza onarım',
            'Didim, Altınkum, Akbük ve Bozbük servis ağı',
        ],
        steps: [
            { title: 'İhtiyacı belirleme', desc: 'Metrekare, kullanım alanı ve beklentinize göre doğru Hisense klima kapasitesi belirlenir.' },
            { title: 'Ücretsiz keşif', desc: 'Montaj noktası, borulama hattı ve elektrik altyapısı yerinde kontrol edilir.' },
            { title: 'Satış ve montaj', desc: 'Onayınız sonrası cihaz teslimi ve profesyonel montaj planlanır.' },
            { title: 'Servis desteği', desc: 'Bakım, arıza onarım ve garanti süreçlerinde Pusula İklimlendirme destek verir.' },
        ],
        faqs: [
            {
                q: 'Didim’de Hisense klima yetkili servisi kim?',
                a: 'Pusula İklimlendirme, Didim’de Hisense klima yetkili bayi ve servis hizmeti sunar. Satış, montaj, bakım ve arıza onarım için iletişime geçebilirsiniz.',
            },
            {
                q: 'Hisense klima montajında keşif ücretsiz mi?',
                a: 'Evet. Didim ve yakın çevresinde Hisense klima montajı için ücretsiz keşif imkanı sunuyoruz.',
            },
            {
                q: 'Hisense klima fiyatına montaj dahil mi?',
                a: 'Güncel kampanya ve stok durumuna göre fiyatlandırma değişebilir. Paylaşılan fiyat listelerinde belirtilen koşullara göre 4 metre borulama ve montaj dahil seçenekler sunulabilir.',
            },
        ],
        related: ['montaji', 'bakimi', 'tamiri'],
        serviceName: 'Hisense Klima Yetkili Servis ve Bayi',
    },
    vrf: {
        slug: 'didim-vrf-servisi',
        title: 'Didim VRF / VRV Sistemleri | Üntes, Midea ve Daikin Projeleri',
        description: 'Didim’de Üntes ve Midea VRF yetkili bayi ve servis; Daikin VRV / VRF proje odaklı çözümler. Keşif, proje, montaj ve bakım için Pusula İklimlendirme.',
        h1: 'Didim VRF Servisi',
        subtitle: 'Otel, restoran, villa ve ticari binalar için VRF sistemlerinde keşif, proje, montaj ve servis.',
        ctaHeading: 'VRF Sistemleri İçin Projeli Çözüm',
        intro: [
            'Pusula İklimlendirme, Didim ve Aydın çevresinde VRF sistemleri için satış, proje, montaj, bakım ve arıza onarım hizmeti sunar. Üntes ve Midea VRF sistemlerinde yetkili bayi ve servis desteği sağlıyor; Daikin VRV / VRF sistemlerinde proje odaklı iş ortaklığı yürütüyoruz.',
            'Otel, apart, restoran, plaza, villa ve çok odalı işletmelerde doğru kapasite hesabı, dış ünite konumlandırması, hat planlaması ve periyodik bakım süreçlerini uçtan uca yönetiyoruz.',
        ],
        answerBox: 'Didim’de VRF sistemi kurulumu ve servisi için Pusula İklimlendirme; keşif, proje, montaj, bakım ve arıza onarım desteği verir.',
        features: [
            'Üntes ve Midea VRF yetkili bayi ve servis',
            'Daikin VRV / VRF proje odaklı iş ortaklığı',
            'Projelendirme ve kapasite hesabı',
            'Otel ve ticari işletme çözümleri',
            'Periyodik bakım anlaşmaları',
            'Merkezi kontrol ve zon yönetimi',
            'Acil arıza ve teknik destek',
        ],
        steps: [
            { title: 'Keşif', desc: 'Bina yapısı, oda sayısı, kullanım senaryosu ve enerji ihtiyacı değerlendirilir.' },
            { title: 'Proje', desc: 'VRF kapasite hesabı, cihaz seçimi ve borulama güzergahı planlanır.' },
            { title: 'Kurulum', desc: 'Montaj, vakum, kaçak testi ve devreye alma işlemleri uygulanır.' },
            { title: 'Bakım', desc: 'Sistemin verimli çalışması için periyodik bakım ve arıza desteği sağlanır.' },
        ],
        faqs: [
            {
                q: 'VRF sistemi hangi işletmeler için uygundur?',
                a: 'VRF sistemleri otel, apart, restoran, ofis, plaza, villa ve çok odalı ticari yapılarda bölgesel iklimlendirme için uygundur.',
            },
            {
                q: 'Didim’de VRF keşfi yapıyor musunuz?',
                a: 'Evet. Didim ve Aydın çevresinde VRF sistemleri için yerinde keşif ve proje değerlendirmesi yapıyoruz.',
            },
            {
                q: 'VRF sistemlerinde periyodik bakım gerekli mi?',
                a: 'Evet. VRF sistemlerinde filtre, gaz basıncı, drenaj, elektronik kontrol ve dış ünite kontrolleri düzenli yapılmalıdır.',
            },
        ],
        related: ['ticari', 'isiPompasi', 'gunesEnerjisi', 'sogukHava'],
        serviceName: 'VRF Sistemi Satış, Montaj ve Servis',
    },
    isiPompasi: {
        slug: 'didim-isi-pompasi-servisi',
        title: 'Didim Isı Pompası | Baymak, Nibe, Üntes, LG ve Solimpeks',
        description: 'Didim’de Üntes, Nibe, LG monoblok, Solimpeks ve Baymak ısı pompası çözümleri. Keşif, satış, montaj, bakım ve havuz ısı pompası desteği.',
        h1: 'Didim Isı Pompası Servisi',
        subtitle: 'Konut, villa ve işletmeler için ısı pompası keşif, satış, montaj ve bakım çözümleri.',
        ctaHeading: 'Isı Pompasında Doğru Keşif ve Verimli Kurulum',
        intro: [
            'Pusula İklimlendirme, Didim ve Aydın çevresinde ısı pompası sistemleri için keşif, satış, montaj, bakım ve arıza onarım hizmeti sunar.',
            'Üntes Grubu, Nibe, LG monoblok ve Solimpeks Grubu ısı pompalarında yetkili bayi ve servis desteğiyle konut, villa, otel ve işletmelere enerji verimli çözümler planlıyoruz.',
            'Baymak ısı pompası çözümleriyle de çalışıyoruz. Havuz uygulamalarını ayrı bir hizmet kapsamında ele alıyor; Baymak ve Varmeks havuz ısı pompalarında hacim, kullanım dönemi ve tesisata uygun seçim yapıyoruz.',
            'Isı pompası dışındaki ısıtma ihtiyaçlarınız için Termodinamik ısıtma sistemlerinde yetkili bayi ve servis desteği de sunuyoruz. Mevcut tesisat, kullanım ve cihaz kapsamını keşifte değerlendirerek uygun çözümü öneriyoruz.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de Üntes, Nibe, LG monoblok, Solimpeks ve Baymak ısı pompası çözümleri sunar. Havuz ısı pompalarında Baymak ve Varmeks ile keşif, seçim, kurulum ve bakım planlar.',
        features: [
            'Üntes ısı pompası yetkili bayi ve servis',
            'Nibe ısı pompası çözümleri',
            'LG monoblok ısı pompası',
            'Solimpeks ısı pompası',
            'Baymak ısı pompası çözümleri',
            'Baymak ve Varmeks havuz ısı pompaları',
            'Villa ve işletme keşfi',
            'Periyodik bakım ve arıza desteği',
        ],
        steps: [
            { title: 'Isı ihtiyacı hesabı', desc: 'Alan, yalıtım, kullanım ve mevcut tesisat bilgileri değerlendirilir.' },
            { title: 'Sistem seçimi', desc: 'İhtiyaca göre monoblok, split veya hibrit çözümler önerilir.' },
            { title: 'Kurulum', desc: 'Hidrolik bağlantılar, elektrik altyapısı ve devreye alma işlemleri yapılır.' },
            { title: 'Verim takibi', desc: 'Bakım ve kontrollerle sistemin verimli çalışması desteklenir.' },
        ],
        faqs: [
            {
                q: 'Isı pompası Didim ikliminde verimli çalışır mı?',
                a: 'Evet. Didim’in ılıman iklimi ısı pompası verimliliği için avantajlıdır. Doğru kapasite ve doğru kurulumla konforlu kullanım sağlanır.',
            },
            {
                q: 'Isı pompası için ücretsiz keşif yapıyor musunuz?',
                a: 'Evet. Didim ve yakın çevresinde ısı pompası kurulumu için yerinde keşif ve ihtiyaç analizi yapılır.',
            },
            {
                q: 'Hangi ısı pompası markalarında hizmet veriyorsunuz?',
                a: 'Üntes Grubu, Nibe, LG monoblok ve Solimpeks Grubu ısı pompalarında yetkili bayi ve servis desteğimiz var. Baymak ısı pompası çözümleriyle de çalışıyoruz. Havuz ısı pompalarında ise Baymak ve Varmeks markalarını değerlendiriyoruz.',
            },
        ],
        childServices: ['havuzIsiPompasi'],
        related: ['havuzIsiPompasi', 'vrf', 'gunesEnerjisi', 'montaji'],
        serviceName: 'Isı Pompası Satış, Montaj ve Servis',
    },
    havuzIsiPompasi: {
        slug: 'didim-havuz-isi-pompasi',
        parent: 'isiPompasi',
        title: 'Didim Havuz Isı Pompası | Baymak ve Varmeks | Pusula',
        description: 'Didim’de Baymak ve Varmeks havuz ısı pompası çözümleri. Villa, otel ve işletme havuzları için keşif, cihaz seçimi, montaj ve bakım.',
        h1: 'Didim Havuz Isı Pompası',
        subtitle: 'Baymak ve Varmeks ile villa, otel ve işletme havuzlarına özel ısıtma çözümleri.',
        ctaHeading: 'Havuzunuza Uygun Isı Pompasını Birlikte Seçelim',
        intro: [
            'Havuz ısı pompaları, havuz suyunun hedeflenen sıcaklıkta tutulması için kullanılır. Pusula İklimlendirme olarak Didim, Akbük, Altınkum ve Aydın çevresinde Baymak ve Varmeks markalarıyla havuz ısı pompası çözümleri sunuyoruz.',
            'Villa, otel ve işletme havuzlarında yalnızca su hacmine göre seçim yapmıyoruz. Açık veya kapalı havuz yapısı, kullanım dönemi, hedef su sıcaklığı, havuz örtüsü ve mevcut filtrasyon tesisatını keşifte birlikte değerlendiriyoruz.',
            'Cihaz kapasitesi, hidrolik bağlantılar, elektrik altyapısı ve ünite konumu proje ihtiyacına göre planlanır. Kurulum sonrası çalışma kontrolleri, kullanım bilgilendirmesi ve bakım takvimi paylaşılır; ürün ve işlem kapsamı teklif aşamasında netleştirilir.',
        ],
        answerBox: 'Havuz ısı pompası, Isı Pompaları hizmet grubumuzun özel bir alt hizmetidir. Baymak ve Varmeks ile keşif, cihaz seçimi, kurulum ve bakım süreçlerini havuzunuzun koşullarına göre planlıyoruz.',
        features: [
            'Baymak ve Varmeks havuz ısı pompası çözümleri',
            'Villa, otel ve işletme havuzları',
            'Hacim, kullanım dönemi ve sıcaklık hedefi analizi',
            'Mevcut filtrasyon tesisatına uygun bağlantı planı',
            'Ünite konumu ve elektrik altyapısı kontrolü',
            'Devreye alma, kullanım ve periyodik bakım desteği',
        ],
        steps: [
            { title: 'Havuz keşfi', desc: 'Su hacmi, açık veya kapalı havuz yapısı, kullanım dönemi ve mevcut tesisat incelenir.' },
            { title: 'Cihaz ve teklif', desc: 'Baymak ve Varmeks seçenekleri ihtiyaca göre değerlendirilir; kapasite, bağlantı ve işlem kapsamı teklif edilir.' },
            { title: 'Kurulum ve test', desc: 'Hidrolik ve elektrik bağlantıları yapılır; su akışı ve cihazın çalışma değerleri kontrol edilir.' },
            { title: 'Kullanım ve bakım', desc: 'Sıcaklık ayarları, kullanım koşulları ve bakım takvimi kullanıcıyla paylaşılır.' },
        ],
        faqs: [
            { q: 'Havuz ısı pompasında hangi markalarla çalışıyorsunuz?', a: 'Havuz ısı pompası uygulamalarında Baymak ve Varmeks markalarıyla çalışıyoruz. Uygun model, kapasite ve uygulama kapsamını keşifte belirliyoruz.' },
            { q: 'Havuz için kapasiteyi nasıl belirliyorsunuz?', a: 'Havuz hacmiyle birlikte açık veya kapalı yapı, kullanım dönemi, hedef su sıcaklığı, örtü kullanımı ve tesisat koşullarını değerlendiriyoruz. Tek başına metrekare veya hacim bilgisiyle kesin cihaz seçimi yapmıyoruz.' },
            { q: 'Konut ısı pompası ile havuz ısı pompası aynı mı?', a: 'Havuz uygulaması için havuz suyuna, tesisatına ve çalışma koşullarına uygun cihaz seçilmelidir. Konut ısıtması için seçilmiş bir cihazın havuza doğrudan uygun olduğunu varsaymıyoruz; ürünün teknik kapsamını kontrol ediyoruz.' },
            { q: 'Mevcut havuza kurulum yapabilir misiniz?', a: 'Mevcut filtrasyon hattı, su akışı, montaj alanı ve elektrik altyapısı keşifte değerlendirilir. Kurulumun uygunluğu ve gerekli ek bağlantılar bu inceleme sonucunda netleştirilir.' },
        ],
        related: ['isiPompasi', 'vrf', 'gunesEnerjisi'],
        serviceName: 'Havuz Isı Pompası Keşif, Satış, Montaj ve Bakım',
    },
    gunesEnerjisi: {
        slug: 'didim-gunes-enerjisi-sistemleri',
        title: 'Didim Güneş Enerjisi Sistemleri | Panel, İnverter, Batarya',
        description: 'Didim güneş enerjisi sistemleri kurulumu. Solimpeks ve Panasonic panel, Kopp inverter ve batarya çözümleri için keşif ve montaj.',
        h1: 'Didim Güneş Enerjisi Sistemleri',
        subtitle: 'Konut ve işletmeler için fotovoltaik panel, inverter, batarya ve kurulum çözümleri.',
        ctaHeading: 'Güneş Enerjisi İçin Yerinde Keşif',
        intro: [
            'Pusula İklimlendirme, Didim ve Aydın çevresinde güneş enerjisi sistemleri için keşif, ürün seçimi, kurulum ve teknik destek hizmeti verir.',
            'Solimpeks ve Panasonic Grubu fotovoltaik panel; Kopp Grubu inverter ve batarya sistemleriyle konut, villa ve işletmeler için enerji verimli çözümler planlıyoruz.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de güneş enerjisi sistemleri için panel, inverter, batarya, keşif ve kurulum desteği sağlar.',
        features: [
            'Solimpeks ve Panasonic panel',
            'Kopp inverter ve batarya',
            'Konut ve işletme keşfi',
            'Çatı uygunluk kontrolü',
            'Kurulum ve devreye alma',
            'Teknik servis ve bakım',
        ],
        steps: [
            { title: 'Enerji analizi', desc: 'Tüketim, çatı yapısı, gölge durumu ve kurulum alanı incelenir.' },
            { title: 'Sistem tasarımı', desc: 'Panel, inverter ve batarya ihtiyaçları belirlenir.' },
            { title: 'Kurulum', desc: 'Montaj, bağlantı ve devreye alma işlemleri planlanır.' },
            { title: 'Bakım', desc: 'Sistem performansı için periyodik kontrol ve teknik destek sağlanır.' },
        ],
        faqs: [
            {
                q: 'Didim’de güneş enerjisi sistemi için keşif yapıyor musunuz?',
                a: 'Evet. Didim ve Aydın çevresinde çatı uygunluğu, tüketim ve sistem ihtiyacı için yerinde keşif yapıyoruz.',
            },
            {
                q: 'Hangi panel ve inverter gruplarıyla çalışıyorsunuz?',
                a: 'Solimpeks ve Panasonic Grubu fotovoltaik panel; Kopp Grubu inverter ve batarya çözümleri sunuyoruz.',
            },
            {
                q: 'Güneş enerjisi sistemi bakımı gerekiyor mu?',
                a: 'Evet. Panel temizliği, bağlantı kontrolleri ve inverter performans kontrolleri sistem verimliliği için önemlidir.',
            },
        ],
        related: ['isiPompasi', 'vrf', 'montaji'],
        serviceName: 'Güneş Enerjisi Sistemi Kurulum ve Servis',
    },
    sogukHava: {
        slug: 'didim-soguk-hava-deposu-servisi',
        title: 'Didim Soğuk Hava Deposu Servisi | Ticari Soğutma',
        description: 'Didim soğuk hava deposu servisi, bakım, onarım ve kurulum. Restoran, market, otel ve ticari işletmeler için soğutma çözümleri.',
        h1: 'Didim Soğuk Hava Deposu Servisi',
        subtitle: 'Ticari işletmeler için soğuk hava deposu bakım, onarım, montaj ve acil servis desteği.',
        ctaHeading: 'Ticari Soğutmada Kesintisiz Destek',
        intro: [
            'Pusula İklimlendirme, Didim ve Aydın çevresinde soğuk hava deposu ve ticari soğutma sistemleri için bakım, arıza onarım ve kurulum hizmeti sunar.',
            'Restoran, market, otel, gıda işletmesi ve depo alanlarında sıcaklık stabilitesi, enerji verimliliği ve acil arıza müdahalesi için teknik destek sağlıyoruz.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de soğuk hava deposu bakım, onarım, montaj ve acil servis hizmeti verir.',
        features: [
            'Soğuk hava deposu bakımı',
            'Ticari soğutma arıza onarımı',
            'Restoran, market ve otel çözümleri',
            'Gaz kaçağı ve performans kontrolü',
            'Periyodik bakım planı',
            'Acil servis desteği',
        ],
        steps: [
            { title: 'Arıza veya keşif talebi', desc: 'Depo tipi, sıcaklık ihtiyacı ve mevcut sorun bilgisi alınır.' },
            { title: 'Yerinde kontrol', desc: 'Kompresör, evaporatör, kondenser, gaz ve elektrik kontrolleri yapılır.' },
            { title: 'Çözüm ve onay', desc: 'Onarım veya kurulum planı net fiyatla sunulur.' },
            { title: 'Teslim ve takip', desc: 'Sıcaklık performansı test edilir, bakım önerileri paylaşılır.' },
        ],
        faqs: [
            {
                q: 'Soğuk hava deposu arızasında acil servis veriyor musunuz?',
                a: 'Evet. Didim ve çevresindeki ticari işletmeler için soğuk hava deposu arızalarında acil teknik destek sağlıyoruz.',
            },
            {
                q: 'Soğuk hava deposu bakımı ne sıklıkla yapılmalı?',
                a: 'Kullanım yoğunluğuna göre periyodik bakım planlanmalıdır. Gıda işletmelerinde düzenli kontrol ürün güvenliği ve enerji verimliliği için önemlidir.',
            },
            {
                q: 'Yeni soğuk hava deposu kurulumu yapıyor musunuz?',
                a: 'Evet. İşletme ihtiyacına göre kapasite, izolasyon, cihaz seçimi ve kurulum planlaması yapıyoruz.',
            },
        ],
        related: ['vrf', 'tamiri', 'bakimi'],
        serviceName: 'Soğuk Hava Deposu Bakım, Onarım ve Kurulum',
    },
    gazDolumu: {
        slug: 'didim-klima-gaz-dolumu',
        title: 'Didim Klima Gaz Dolumu | Kaçak Tespiti ve Servis',
        description: 'Didim klima gaz dolumu, gaz kaçağı tespiti, soğutmama arızası ve klima servis hizmeti. Pusula İklimlendirme ile yerinde çözüm.',
        h1: 'Didim Klima Gaz Dolumu',
        subtitle: 'Soğutmama, eksik gaz ve kaçak şüphesinde yerinde kontrol ve teknik servis.',
        ctaHeading: 'Klima Gaz Dolumu İçin Servis Talebi Oluşturun',
        intro: [
            'Klima gazı eksikliği genellikle soğutmama, geç soğutma, buzlanma veya düşük performansla kendini gösterir. Pusula İklimlendirme, Didim ve çevresinde klima gaz kontrolü, kaçak tespiti ve gaz dolumu hizmeti sunar.',
            'Gaz dolumu yapılmadan önce kaçak ihtimali kontrol edilir. Böylece yalnızca gaz eklemek yerine sorunun kaynağına yönelik kalıcı çözüm hedeflenir.',
        ],
        answerBox: 'Pusula İklimlendirme, Didim’de klima gaz dolumu ve gaz kaçağı tespiti hizmeti verir. Soğutmama ve buzlanma sorunlarında yerinde servis sağlar.',
        features: [
            'Klima gaz basıncı kontrolü',
            'Gaz kaçağı tespiti',
            'Soğutmama arızası kontrolü',
            'Split ve ticari klima servisi',
            'Drenaj ve filtre kontrolü',
            'Yerinde teknik destek',
        ],
        steps: [
            { title: 'Ön kontrol', desc: 'Cihazın soğutma performansı, filtreleri ve çalışma değerleri kontrol edilir.' },
            { title: 'Kaçak değerlendirmesi', desc: 'Gaz eksilmesine neden olabilecek bağlantı veya hat sorunları incelenir.' },
            { title: 'Gaz dolumu', desc: 'Uygun gaz tipi ve cihaz değerlerine göre dolum yapılır.' },
            { title: 'Test', desc: 'Çıkış sıcaklığı, basınç ve genel performans tekrar kontrol edilir.' },
        ],
        faqs: [
            {
                q: 'Klima gazı biter mi?',
                a: 'Normal çalışan kapalı devre klima sisteminde gaz tüketilmez. Gaz eksilmesi çoğunlukla kaçak veya bağlantı sorunu belirtisidir.',
            },
            {
                q: 'Gaz dolumu yapılmadan önce kaçak kontrolü gerekir mi?',
                a: 'Evet. Kaçak kontrolü yapılmadan sadece gaz eklemek sorunun kısa sürede tekrarlamasına neden olabilir.',
            },
            {
                q: 'Didim’de klima gaz dolumu için servis veriyor musunuz?',
                a: 'Evet. Didim, Altınkum, Akbük, Bozbük ve yakın bölgelerde klima gaz dolumu ve kaçak tespiti hizmeti veriyoruz.',
            },
        ],
        related: ['tamiri', 'bakimi', 'montaji'],
        serviceName: 'Klima Gaz Dolumu ve Kaçak Tespiti',
    },
};

export const getLandingBySlug = (slug) =>
    Object.values(landingPages).find((page) => page.slug === slug);
